name: 'Terraform CI'
description: 'Validate and runs a terraform plan'
inputs:
  terraform_version:
    description: 'Terraform version to use'
    required: False
    default: '0.14.x'
  # Currently is not allowed to use conditional inside composite actions. https://github.com/actions/runner/issues/834
  # write_plan_as_comment:
  #   description: 'enable to write the tfplan to the pr comment'
  #   required: false
  #   default: true
runs:
  using: composite
  steps:
    # to calculate the hash of the files without the current dirty workspace
    - name: checkout original repo
      uses: actions/checkout@v2
      with:
        path: .original_repo
    # Just to discard possible differences if the commit sha is not the same between
    - name: clean up .git from original repo
      shell: bash
      run: rm -rf .original_repo/.git
    - name: get original repo hash
      id: repo-hash
      shell: bash
      run: echo "::set-output name=hash::${{ hashFiles('.original_repo/*') }}"
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: true
    - name: terraform init
      env:
        TF_IN_AUTOMATION: 1
      shell: bash
      run: |
        terraform init -input=false \
          -backend-config=container_name=$TERRAFORM_BACKEND_TFSTATE_CONTAINER_NAME \
          -backend-config=key=$TERRAFORM_BACKEND_TFSTATE_NAME \
          -backend-config=storage_account_name=$TERRAFORM_BACKEND_TFSTATE_STA_NAME \
          -backend-config=resource_group_name=$TERRAFORM_BACKEND_TFSTATE_RG_NAME
    - name: cache tfplan
      uses: actions/cache@v2
      with:
        path: tfplan
        key: "tfplan-${{ steps.repo-hash.outputs.hash }}"
    - name: terraform plan
      env:
        TF_IN_AUTOMATION: 1
      shell: bash
      run: |
        terraform plan -input=false -out tfplan
    - name: capture terraform plan
      env:
        TF_IN_AUTOMATION: 1
      id: tfplan_plain
      shell: bash
      run: |
        # Adds the plan in plain text to a env var called TFPLAN. Used to write the comment in the PR
        terraform show -no-color tfplan
    - uses: actions/github-script@v5
      name: Add plan to PR comment
      # if: ${{ inputs.write_plan_as_comment }}
      # Currently is not allowed to use conditional inside composite actions. https://github.com/actions/runner/issues/834
      env:
        PR_COMMENT_BODY: |
          ```hcl
          ${{ steps.tfplan_plain.outputs.stdout }}
          ```
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.PR_COMMENT_BODY
          })
